// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynykttmjvcoztdgrcycv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlueWt0dG1qdmNvenRkZ3JjeWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzU5MTgsImV4cCI6MjA2NDIxMTkxOH0.mumSCBq-7WkpjMT2_eoy3v9mILBKPzR9OZtoAW8TTUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);